<a href="https://colab.research.google.com/github/veliyorganci/Assigment_1/blob/main/Assignment_01_Student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [ ]:
# YOUR CODE IS HERE

import numpy as np
import pandas as pd
import random as rand

### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [ ]:
# YOUR CODE IS HERE
my_list = np.array([5, 10, 15, 20, 25])
my_list


array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [ ]:
# YOUR CODE IS HERE
np.zeros((5, 5), dtype = int)



array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [ ]:
# YOUR CODE IS HERE
np.ones((4,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [ ]:
# YOUR CODE IS HERE
np.full((4,4), 7)


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [ ]:
# YOUR CODE IS HERE

np.full((4,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [ ]:
# YOUR CODE IS HERE
np.arange(2, 17, 2)


array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [ ]:
# YOUR CODE IS HERE
crea = np.arange(25)
crea

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
crea.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [ ]:
# YOUR CODE IS HERE
crea2 = np.linspace(0,24, 25).reshape(5,5)
crea2

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

### 10. Create randomly 5 numbers with numpy.

In [ ]:
# YOUR CODE IS HERE
import numpy as np
from scipy import stats
import pandas as pd
import random as rand
import seaborn as sns


In [ ]:
from numpy import random

In [ ]:
x = random.rand(1, 5)

print(x)

[[0.44204298 0.02351112 0.36254097 0.09398096 0.65253759]]


### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [ ]:
# YOUR CODE IS HERE
randvalue= np.random.rand(5,5)
randvalue


array([[0.39627199, 0.96596626, 0.97664245, 0.30727401, 0.02434443],
       [0.89825473, 0.62778562, 0.20834389, 0.6020792 , 0.52757415],
       [0.3487303 , 0.16635647, 0.66240923, 0.535646  , 0.63284961],
       [0.12368386, 0.36506966, 0.31724626, 0.25207304, 0.80394974],
       [0.29498016, 0.31362916, 0.88719308, 0.97005668, 0.6715881 ]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [ ]:
# YOUR CODE IS HERE
crea3 = np.random.randint(20, 50, size = (3,4))
crea3

array([[34, 38, 40, 47],
       [32, 28, 27, 44],
       [46, 34, 47, 30]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [ ]:
# YOUR CODE IS HERE

ranarr = np.random.randint(1,100,48)
ranarr

array([57, 52, 85, 23,  4, 43, 26, 44, 66, 43, 21, 60, 55, 10, 62, 65, 93,
       61, 55, 41, 77, 77, 42, 46, 97, 83, 22, 81, 70, 18, 44, 88, 59, 14,
       33, 20, 21,  1, 43, 43,  8, 25,  1, 98, 58, 82, 91, 97])

In [ ]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)

ranarr2 = ranarr.reshape(6,8)
ranarr2

array([[57, 52, 85, 23,  4, 43, 26, 44],
       [66, 43, 21, 60, 55, 10, 62, 65],
       [93, 61, 55, 41, 77, 77, 42, 46],
       [97, 83, 22, 81, 70, 18, 44, 88],
       [59, 14, 33, 20, 21,  1, 43, 43],
       [ 8, 25,  1, 98, 58, 82, 91, 97]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [ ]:
import numpy as np
from scipy import stats
import pandas as pd
import random as rand
import seaborn as sns

In [ ]:
# YOUR CODE IS HERE 
mat = np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
np.split(mat, [1, 3], axis = 0)


[array([[1, 2, 3, 4]]), array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])]

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [ ]:
# YOUR CODE IS HERE 

mat[1:3, 1:3:]


array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [ ]:
# YOUR CODE IS HERE array([[ 1, 2, 3, 4], [ 5, 6, 7, 8], [ 9, 10, 11, 12], [13, 14, 15, 16]])

mat[:,0]

array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [ ]:
#  array([[ 1, 2, 3, 4], [ 5, 6, 7, 8], [ 9, 10, 11, 12], [13, 14, 15, 16]])
mat[1,:3:2]


array([5, 7])

### 17.Assign 77 to every cell in 3rd column.

In [ ]:
# YOUR CODE IS HERE 
mat2 = np.array([[ 1, 2, 3, 4], [ 5, 6, 7, 8], [ 9, 10, 11, 12], [13, 14, 15, 16]])
mat2[:4,2:3] = 77
mat2

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [ ]:
# YOUR CODE IS HERE 
mat2[(1,0),(3,2)]



array([ 8, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [ ]:
# YOUR CODE IS HERE 
# array([[ 1,  2, 77,  4],[ 5,  6, 77,  8],[ 9, 10, 77, 12],[13, 14, 77, 16]])

mat2[1:4:2, 0:3:2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

:### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [ ]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat" 

# YOUR CODE IS HERE 

mat[(mat < 10) ]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 
mat[(mat > 12)]


array([13, 14, 15, 16])

In [ ]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 
mat[(mat < 10) | (mat > 12)].sum()


103

### 21. Get the standard deviation (std) of the result above.

In [ ]:
# YOUR CODE IS HERE 

mat.std()

4.6097722286464435

### 22. Get the sum of the 2nd column in the original "mat".

In [ ]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# YOUR CODE IS HERE 
second_column_sum = mat[:, 1].sum()
print(second_column_sum )

32


### 23. Get the median, mean and std of 3rd column in "mat".

*   Liste öğesi
*   Liste öğesi



In [ ]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 

# YOUR CODE IS HERE 

arr = mat[:,2]
arr

array([ 3,  7, 11, 15])

In [ ]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 

# YOUR CODE IS HERE 

arr2 = mat[2,:]
arr2

array([ 9, 10, 11, 12])

In [ ]:
# LET US GET MEDIAN VALUE 

# YOUR CODE IS HERE 

np.median(arr)


9.0

In [ ]:
# LET US GET MEAN VALUE 

# YOUR CODE IS HERE 
np.mean(arr)
np.mean(arr2)

10.5

In [ ]:
# LET US GET STANDART DEVIATION (std) VALUE 

# YOUR CODE IS HERE 

np.std(arr)
np.std(arr2)

1.118033988749895

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [ ]:
import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [ ]:
# LET US READ Salaries.csv 

# YOUR CODE IS HERE 

df = pd.read_csv('/content/Salaries.csv')
df

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [ ]:
# LET US LOOK AT THE FIRST 5 ROWS 

# YOUR CODE IS HERE 

df.head(5)

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [ ]:
# LET US GET A SAMPLE 

# YOUR CODE IS HERE 

df.sample()

Id     EmployeeName       JobTitle   BasePay  OvertimePay  OtherPay  \
99934  99935  Cynthia M Gozun  Special Nurse  59815.44          0.0   2130.98   

       Benefits  TotalPay  TotalPayBenefits  Year  Notes         Agency  \
99934    619.52  61946.42          62565.94  2013    NaN  San Francisco   

       Status  
99934     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [ ]:
# YOUR CODE IS HERE 

df = pd.DataFrame
df

pandas.core.frame.DataFrame

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [ ]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS  

# YOUR CODE IS HERE 

df.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [ ]:
# YOUR CODE IS HERE 

df.Year.value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [ ]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"
df.Year.nunique()
# YOUR CODE IS HERE 



4

In [ ]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 

df.Year.unique()

array([2011, 2012, 2013, 2014])

### Print out max and avg values in the column of "Totalpay".

In [ ]:
# LET US FIND THE MAXIMUM TOTALPAY

df['TotalPay'].max()



567595.43

In [ ]:
# LET US FIND THE AVERAGE TOTALPAY

df['TotalPay'].mean()



74768.32197169267

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [ ]:
# YOUR CODE IS HERE 

# LET US FIND THE AVERAGE TOTALPAY

df[df['TotalPay']]>df[['TotalPay'].mean()]

KeyError: ignored

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [ ]:
# YOUR CODE IS HERE 

f[df['TotalPay']>df['TotalPay'].mean()].shape[0]

NameError: ignored

### How much does ALBERT PARDINI make money (including benefits)?

In [ ]:
# YOUR CODE IS HERE 
df[df['EmployeeName'] == 'ALBERT PARDINI']['TotalPayBenefits']


2    335279.91
Name: TotalPayBenefits, dtype: float64

### Who is the lowest paid person?

In [ ]:
# YOUR CODE IS HERE 

df[df['TotalPayBenefits']  == df['TotalPayBenefits'].min()]['EmployeeName']

148653    Joe Lopez
Name: EmployeeName, dtype: object

### What are the unique Jobs in dataset?

In [ ]:
# YOUR CODE IS HERE 

df['JobTitle'].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

### List the top 3 least common Jobs in the dataset.

In [ ]:
# YOUR CODE IS HERE 

df['JobTitle'].value_counts().tail(3)

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

### How many people earned more than avg in 2012?

### How many people have a title of Manager in their jobs?

In [ ]:
# USE APPLY FUNCTION

# YOUR CODE IS HERE 



### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________